language: go

go:
  - 1.5.4
  - 1.6

services:
  - redis-server
  - docker

install:
  - make dependencies

script:
  - make stat
  - make test

after_success:
  - make clean docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/nsproxy unixvoid/nsproxy:develop
  - docker push unixvoid/nsproxy:develop
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/nsproxy*` --form path=nsproxy/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/nsproxy*` --form filename=nsproxy-latest-linux-amd64 --form path=nsproxy/ https://cryo.unixvoid.com/upload
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  - make clean travisaci
  - mv nsproxy.aci nsproxy-latest-linux-amd64.aci
  - make signaci
  - curl -i --form sec=$BINDER_SEC --form file=@nsproxy-latest-linux-amd64.aci --form path=rkt/nsproxy/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@nsproxy-latest-linux-amd64.aci.asc --form path=rkt/nsproxy/ https://cryo.unixvoid.com/upload
