language: go

go:
  - 1.5.4
  - 1.6

services:
  - redis-server

install:
  - make dependencies

script:
  - make stat
  - make test

after_success:
  - make clean
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/nsproxy unixvoid/nsproxy:develop
  - docker push unixvoid/nsproxy
